const pass = require('./password');

test('isPasswordValid', () => {
    result = pass('helloworld1');
    expect(result).toEqual(false);
    result = pass('tttt3');
    expect(result).toEqual(false);
    result = pass('33333333333');
    expect(result).toEqual(false);
    result = pass('AAAAAAAAAAAA');
    expect(result).toEqual(false);
    result = pass('1AAAAAAAAAAA');
    expect(result).toEqual(false);
    result = pass('1AAAAAAAAAAA$');
    expect(result).toEqual(true);
    result = pass('*AAAA1AAAAAA');
    expect(result).toEqual(true);
    result = pass('*AAAA1AA', 10);
    expect(result).toEqual(false);
    result = pass('$2AAA12222A$2A', 5, 10, 5, "[$]");
    expect(result).toEqual(false);
    result = pass('*2AAA1A2A', 5, 3, 5, "[$]");
    expect(result).toEqual(false);
    result = pass('$2AA1A2A', 5, 3, 5, "[$]");
    expect(result).toEqual(false);
    result = pass('$2AAA2BA', 5, 3, 5, "[$]");
    expect(result).toEqual(false);
    result = pass('$AAs1C2322', 5, 3, 5, "[$]");
    expect(result).toEqual(true);
});